---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-ntfy
  namespace: observability
  labels:
    app.kubernetes.io/name: alertmanager-ntfy
    app.kubernetes.io/instance: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager-ntfy
    app.kubernetes.io/instance: observability
  ports:
    - name: http
      port: 8000
      targetPort: http
