---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-ntfy
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: alertmanager-ntfy
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: NTFY_ALERTMANAGER_TOKEN
    - secretKey: webhook_password
      remoteRef:
        key: ALERTMANAGER_NTFY_WEBHOOK_PASSWORD
