apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-local
  namespace: postgres
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  managed:
    roles:
      - name: nextcloud
        login: true
        passwordSecret:
          name: postgres-nextcloud
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
