apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  affinity:
    topologyKey: azalea.io/host
    podAntiAffinityType: required
  storage:
    size: 10Gi
    storageClass: longhorn
  managed:
    roles:
      - name: nextcloud
        login: true
        passwordSecret:
          name: postgres-nextcloud
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
