---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-nextcloud
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: postgres-nextcloud
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: POSTGRES_NEXTCLOUD_USERNAME
    - secretKey: password
      remoteRef:
        key: POSTGRES_NEXTCLOUD_PASSWORD
