apiVersion: v1
kind: Secret
metadata:
    name: postgres-nextcloud
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wPZ7fZRCyqa1,iv:DZGZjQQQiKpmSfUQBvMJwhANWScm+rhDjk69hJaf6So=,tag:GIsxQG57kgvfD3CkaDuE0w==,type:str]
    password: ENC[AES256_GCM,data:M0u4nzRxuSBPQm43b5I5Gw==,iv:tFiwL86UZjgJog4i2nHYhkG6V5IhyzYf+ZBlqZn0kJw=,tag:tDHydOWQr9cW9aoH8jxlYA==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Mk92aGgvRlB3TTJ2WU80
            S2Z0UWh5b2VQYzVmZUJVRE5aSnBnSTFKazBBClRueE81dUU4MG41TFZPeDYrTTZk
            QkVoaHYxOHdPRy9rMFgzVEtzdzVCZWcKLS0tIEtaOGZnMVp2QU5sZlRYRzdxY2Fl
            VGZndXZSVisvNHYyTVNIL21vci9BZFkKSIYbVTp2j1wnTljTGMC47brqw3+3ht/m
            E6/oaMwpWXWIuprSN/5xjr27VYiuvTqRdHdXVdrfpQC0n7RgnHKQVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:33:21Z"
    mac: ENC[AES256_GCM,data:Fle6g+Jw5WeMm0zeVL/tpQ5OChSioKp6vwre5y3PwHAA0qgnzq5e9onvmdbvCQwQZJc4w5tO2S76xdlla/NiemclsuEmkJJC2sv0SkIUNBWAiICfvzxhMPg08LxnS+RgAE6eyeM23tYzYUMPN1niMaFiznSZA+AQkS0taW1cg8Q=,iv:A7IahsKfEB8+epeLcMOCoILSEZRJXKnjqQEEwKlE1Ps=,tag:NO6bCKvJwSyVkkMoXoPBGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
