---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-config
  namespace: ntfy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ntfy-config
    creationPolicy: Owner
  data:
    - secretKey: NTFY_AUTH_DEFAULT_ACCESS
      remoteRef:
        key: NTFY_AUTH_DEFAULT_ACCESS
    - secretKey: NTFY_ALERTMANAGER_TOKEN
      remoteRef:
        key: NTFY_ALERTMANAGER_TOKEN
