apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-pod-data
  namespace: org
  labels:
    app.kubernetes.io/name: ssh-pod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
