apiVersion: v1
kind: ConfigMap
metadata:
  name: azalea-dev-ssh
  namespace: dev
  labels:
    app.kubernetes.io/name: azalea-dev
data:
  authorized_keys: |-
    sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAID3Drv81UCKTs6hb4WRL3is9i6LQ+FjJVPp0/pUmZVOHAAAABHNzaDo= yubikey-1
    sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIPfwXSDdqV3eDT1R3PVyXrX+p+ZOHzKJYjuropbSh8fGAAAABHNzaDo= yubikey-2
