---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azalea-dev-kubeconfig
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: azalea-dev-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: KUBECONFIG
