---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azalea-dev-opencode
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: azalea-dev-opencode
    creationPolicy: Owner
  data:
    - secretKey: OPENCODE_SERVER_PASSWORD
      remoteRef:
        key: OPENCODE_SERVER_PASSWORD
