apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azalea-dev-home
  namespace: dev
  labels:
    app.kubernetes.io/name: azalea-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
