apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: daac1e08-1fcb-4060-9deb-a04a1e035e0f
    ingress:
      - hostname: ssh.pirackr.xyz
        service: ssh://100.90.157.92:22
      - hostname: org.pirackr.xyz
        service: ssh://ssh-pod.org.svc.cluster.local:22
      - hostname: azalea-dev.pirackr.xyz
        service: ssh://azalea-dev.dev.svc.cluster.local:22
      - hostname: "*.pirackr.xyz"
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
