apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/part-of: azalea-homelab
