apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:6w2bhQO+5De8bp9OJKHelZxbdhYUVf5lFu2arAuvIridtS2TcUZgJirvk/SUMFHsB0wUsUn5atB1btxCjbwqFP3KYOTmLVPYGsFeCmAU2y6XG7ZTSNNNNln/NvD/dps0M6UDjpz5XwYlfG7kNaf5Y6yavNT9HBlyN6/Ujw+daV0Ho4dYERikfKwglVcqiug6NHIURviWJO3OIWcUyzTO5rc+Etr29+HjUHBKs/CSZXpIvCkKNvD6Bg==,iv:elymB+czQvAmccd24X+L2egzLoXlG+kJyu8N1CJpfqE=,tag:k0k96N7wOcQT9YiAUzTwhA==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYVYwdWNHVUhnN05NTFp6
            Y2ZzUlJmSGlUam10LzhESXNucDVpMDlpUVgwCmNrYXpPa0xTM3oySGdkMFFtU0Zu
            SC9zWmUrdFc4cDdRTzJ3a2t3VUNWMFEKLS0tIGVUWlExUGhrQXF0dTVhYUsvWnpQ
            QXhCLzRUeTQ2RkVvS25MTXBwWFlnMkUK0O23+XEpolTIAjak/FSRKYzzPMX+Ct3N
            Ur7x/L0q0lxmhUprvY2qqyYdeIIQAmn8fC5qyYWw6Vi9Q6pQDpETXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T00:59:27Z"
    mac: ENC[AES256_GCM,data:5pQrMemF3OWEZMCHXakGaFOM4hNPN9OIsf4NLjs4iuSorrLmohR61cQvlMSRgOdOm2hcEYkDykmQUMyjS2V0Dsw9U6HhoEbbGKhd5MyNGYP5ADP6Alg7oNemVhYuzWXRsaJ5M68LWokJ+HWwWP6KE/na86dWbvgkKF6uZLUtJRs=,iv:6MZrQ8tEgSIfkNhzownFZtLaC7KXIrlogTuf1Bt0LTI=,tag:aoNHdtq2Nm55i/3wgOeEaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
