apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:pLaV52/rnOUGXlhUV4XjxNwrxJzeEcGB5NETCyoi42DLcquzOrsuq6775WD1LKi+6CyJ7WUyeoAd6HnvAuSINBXSt1jcefeBkTP6H9yBR2Pilr/jbk2exdp9R44IEMFgDnTgVxigSkzM2FzKE6W09gGoKHmU7GwIvwBBu4+07JyhKfm2r1+w5VpWjP4NqeZcHDHZVcFedV/9wj3id9zsVDV0tV841ZMNXvGP3U+8iz87GqpO2hs4+A==,iv:svOH6DYAxxaA8g+KD0jkhLt3LUKtu3HHAmn0hG3A078=,tag:guxVbc2JGACxUKOY8/6Wfw==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRmdvbGd1M3JOdk9QeG5O
            czdCS3ljUW9Pc1RreFdzMnc1dlBuL0dYTEI4Ck1kSzRJZjhwSEdpSm1nbWhSOU1o
            ZWMyMGkzSnBqcHlSMmVzU1NyV1FsYnMKLS0tIGZiNmtNbnZOdm1wTFhHZTFHZFVu
            WDF3NUpSSFFKN0wwQU5Nc1REUlJPUGsKj2rHx+hHAaxuV8yDibamYR+9H1qt3gcK
            u/tcK48zdqzA2lhk4HcEdcNL+d/B58gibjGDh4PCOI0GTaqjbc1YYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T05:40:44Z"
    mac: ENC[AES256_GCM,data:t5xTTmbDfPGLY0unwk5W0nJvsWb5wpTjiw4AGY0yNmujX9OgrT4SMdmJkX0FM2G/aPnmfyjZZxogss8aEUuAG+h0vcUPYxXga53SJzTnlG/XmWdXoNg9IZH8zbjL8n3yDHowL4G7PXge7yQpTxIejbazRqfi5ARFx6VL48PnkSM=,iv:0njChalCklGXjuX7l5grzQeuLEp1prMyhzKBrMmCPPg=,tag:cUx8+ivZ0CBAa+sX+gUx8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
