---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: nextcloud-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: NEXTCLOUD_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: NEXTCLOUD_DB_PASSWORD
    - secretKey: database
      remoteRef:
        key: NEXTCLOUD_DB_DATABASE
