apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:HlGVxg==,iv:UYlNltB14Si8F4onXmIhSJrcIUxR7u1pTA+NqmQ6x1E=,tag:6M7+dGdd5UXEbSrhSKqLdQ==,type:str]
    password: ENC[AES256_GCM,data:o/vZs77SuG05W15Tdj+HLg==,iv:qADwWDiRzZt+aTf4hOWIQz5u9Ht4i/tDeWeIyM3QOUU=,tag:vPvjn7INSKkv4KAPpVenTQ==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWEpCbUdPaGNEYTZ2Z0Uy
            ZERwa08zbGFPSU1JM280TCtmd2orMjJoajF3CktGL0o3SlpWK28xTmUzc2R2bGs2
            VFdQRldLekl0NGpmSllKU1U2amZoaUkKLS0tIEh1V2tnZkdwaTQ2ZkdVZ0V4cThF
            c2g4a01HVEtaM3Nyd3o2Q05KbXo5SW8Kqqx2dDhkq/mX/9yvG0vWZh64QIY+0sJO
            cg9v1AtNyXzShoOFnwagc0gDCKynbcKp97d78xOExUbC8uNiGl7f2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:21:30Z"
    mac: ENC[AES256_GCM,data:yR+IyB3TXVU/8C8HnZNQNVCDpI1kucTMNFXsLSjb68uOx2e0hIqwYpLl5RQslUFZbPtZXS0pufj03kmQNh6WAa0WU0GCmloFEv++Mr/rB/Y9LFH8Og4vf1S8qtpgve/NzeLR7WFjUHwkLsnevxWOKdY2B9Mi0tykZM6U6rWvXxo=,iv:mtd8+JlVuEkG71GqAGFnuwMnVHPpvONRzruW5yr4lqI=,tag:Y9sqPKO29MWyjlTAbX9DsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
