apiVersion: ENC[AES256_GCM,data:LJ4=,iv:r4FVja23Tdn2/RAXFIuVKDocDKL41oOd5S3ws2WnDVg=,tag:9APLvDym4H5ViZHQwx/mzg==,type:str]
kind: ENC[AES256_GCM,data:ZJ+LSss1,iv:J/rc+Q0WM7P0urbcsn2x65Bw2YIFEMUCpm5G/OnlD8I=,tag:uYx5DLC+7zUqIOYkam1JxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V/hK8c5uZEO/iO3ftqDK,iv:sHA9MLvHq3YOApjEyueBY6qwzRbXh+p6TjJkXW3r4GM=,tag:tDkce2DXq9na/eicIlYb5A==,type:str]
    namespace: ENC[AES256_GCM,data:HeNhTS7MujFQ,iv:9sDt/7vUB8DPVCuhQp+Nw/JSp0HqBDl0w//kciHIYo4=,tag:/OGDy1JSf+3Ye8wBLCZe+g==,type:str]
type: ENC[AES256_GCM,data:LkXlltIw,iv:Vijggg/AJ0Empk9SNco6QSmYUmTWkVD5H38cgZ1XpD0=,tag:EGsro9lksi9JHncI0zSSIQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:hvDS8g==,iv:TXmGnEjOAtDCBSHo9dug/qBLHameejP+Rl1qX8TRchw=,tag:t93GZePFyu2qBWXshwh4KA==,type:str]
    password: ENC[AES256_GCM,data:zAbY/d1f6//LRtqTBCwo9A==,iv:XhUz52QPGnjZ1ye2RxWd2G1UWrcmEp52vOYZiIpcaPo=,tag:Uf6QR3smjQeN1XL3+Pt6PA==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM1M2YWUrcGIxTE82OXJz
            eGJtblFmMkEvR1BzQWxvb1p4N3FSL0FmWjNrCjlCMHJuTnV1YS92bXpNTmhHOFBX
            MC9GSHpYcjVIZmtRMFQvRXFoaTIzdjAKLS0tIFMvTklsRmVTcHdoQm9RR20wM2ll
            blhrOWtjNzRNa0d5LzJjNXkvczVqUFUKd3p9CZQhy9JwAt+gOQYPBPCWydMhZ1Mi
            j7IUzT+9iFldfmx2IM+D3fzq8j1okw3MjJRM2Y0AHrAkoWJxxrfIrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:10:25Z"
    mac: ENC[AES256_GCM,data:K56MxuEXP9XjJLqAcb53tFmntqKM5+rfE0b3K0zkcMsrTUIafeF2SpLJqotPcyzK7DbyYlR/ewsbQW+wg8iAfRbfswo8ZFrXykrujY9Ibs0qMUBwkWUtGY87s1lur/ZEWSbx964P3wSbJV93RSl9hlxdx9tHMXnckWh+TJmRGKU=,iv:VlDZnoZuaDbWSTxrjcs+TORp50C4YRDry5bjD6ZkfIU=,tag:OVNlXESrbzRnlrmFkEpQcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
