apiVersion: ENC[AES256_GCM,data:+6k=,iv:jl3UpAjTyUYrmfUDL1SrpzUhhtJiHIFAj5V5WocmAn4=,tag:HkmUwFoJid7aFRNX1bjHig==,type:str]
kind: ENC[AES256_GCM,data:YH6ADpO8,iv:lA8fQhUEOg8bWcl8M+FyXTscbArSoGRz8VNX9c3U84g=,tag:rLyJLqhN4Z5SPVD8bivKVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gida8Grm9Sn1pgVY,iv:Gh3BvyWaghv0DonDvQnvyu4tbeV6lBJ8Yax+pAg9amQ=,tag:zlYqtxl2tNzMLISZK7aFhg==,type:str]
    namespace: ENC[AES256_GCM,data:50bDqgNi82Gh,iv:jCxioh9T8IHSkSEueTeK5PR3Fllw2Zy5sUJ1tsL/PG0=,tag:mBH8dI+JG3/SXkyFogagTA==,type:str]
type: ENC[AES256_GCM,data:3iVPYeJU,iv:Xy3IfxqkHDQPA6C4hG63JpLlmCOQnpmVlbIk7S5CqZo=,tag:UUH5XjTwufZpIZrvVwLR4A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:18mkCXOdr4bF,iv:e9cUrbidgzwb/NTjoUlGrVje2LyFG0PKSnZsPnx0xDo=,tag:d7yPZpELbTSnwW9maK6V2Q==,type:str]
    password: ENC[AES256_GCM,data:s2LF4VbUNC+5yk9LgEt46w==,iv:lI910hP0G0PkhpxR+/C16xNahkmvqlnxaTUdZAB7w3E=,tag:DYO8yRtveeNpzilXnMrY/w==,type:str]
    database: ENC[AES256_GCM,data:1kxJGeNmdWre,iv:LxIdAhrB+Zxj/AMXGp0nNe86jzOcJhquWjyCY+RRQJI=,tag:RY1Ym3D83MQvfqUWqzYcbQ==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNDJIZy9YNDgyS21sbi9N
            a1ZBZ0QxS1hGcXYxUFJwMWw0bUhCbmQ0WVFNCnJ4NEpsNzNaamVqMGQwanRYZmxl
            a1lpTDhFaUIzVmNmY09QT2lLOTlyS3cKLS0tIHZYMndkdTB4TE5kbGhYbGVJcFlB
            eEFEQmJzTERZWk42VFBsTUk1QjBIVU0KO4oie6mJHlOQdJW+KDpfhWWW9aKMDxtX
            yReLswEXj14xgCR4993N+bS41EiHQhy0jGfRBkXEyxuadpyv5ah3kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:09:44Z"
    mac: ENC[AES256_GCM,data:fb19mt8R65Pn1sJfi4TdW7M3I+B20j0GbBYR6y7vFgiCHWsyymC+YMpa/WANnDBttbsY+/xbCPFSSwLHqsHbvnz/04tUWfZAQwysXlIAFcOJvH67Qtqu7e5W9+8HmaEj0iaeY/HhzBP8PmTbnz/XCrELHO/Em0Nib7+fyeOYm6w=,iv:YAAcfYeR33SN2UpDT6hsFtgDRLDNFVmFEqrFL1++zaA=,tag:QGyxSiJFZEDzlTYrIa90ag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
