apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ecX2ViecZFG2,iv:1heE+H7CeAsj+Pv2oCZmplXPaQWolmz4eduThwnT1V8=,tag:4hs43gff3g5FIPPY4R4MGw==,type:str]
    password: ENC[AES256_GCM,data:ydZA2AOymQ+O/EpHYgcE8Q==,iv:Qcq/FOxBQ1XfT8mGENquenu7eJt+ZGUE7jcmgLF/6vc=,tag:kqlPNTGFMqK0zmnfdmp9Nw==,type:str]
    database: ENC[AES256_GCM,data:Ynfc5s0rFXxU,iv:iZ98rBnsGAYw6GGAwXBR50elZAWWf7yM8mtOrZEX5O8=,tag:eptsvH7QVCJTXdlR/O1aUA==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S1A5RTl3Y1hVNUF6ZVBo
            ditxeVNBWnQ2WlFTdGsxUkhKZ3dUVTAvTG5vCllKUmZrQmlWUzhDWjV2M3lBMU5z
            MWxreDk1clU0MzRaK2FLMVRZZG9jYWsKLS0tIG02aVZkV0V6NFhaMjBJR3E1cmlH
            dmhZSEtOZC8xd25KUGpXb09iOVNVWlUK9Rd/ldhiwLFPbnc8srJRipmkCNxtJym4
            IO2XqCi7AJeYklWSAUXggJNGZ0BDY48kW7gvX58MgZ6JJIi9b7R6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:21:22Z"
    mac: ENC[AES256_GCM,data:qvnHGlJjI8egqr1s1cPBE+bGDVjOP9xFwvWa0w4JH8bjKz3WyDrpAMwVNlVCI+E4fm1KCvMfhiOp3MGVmg5GR+SsyGPKlZcU0amLeetyb3v0OKrNpleii0PnpADukYKcO3FBs6bLGLuFHSKtjVTTTfDB/xGVqKMfUTd3lm+1oCU=,iv:EcKBIXBk8PPKUoUCePJbMP3DKEqzyl7da7PFldReYu4=,tag:erqWOnoBpSDAHtjFLvVMwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
