apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4ScJ+cM=,iv:5X8+SkDXUr+5hyO1YtUjrfH9X7+UVVRWXlV0wJErruE=,tag:Q1Heloeg83/R7oAofppnsg==,type:str]
    password: ENC[AES256_GCM,data:c9Q23RNdD5vvJIfByUkmq46S7cy7OXg=,iv:E4S6Qd0qMYleCYLL+VI5bRYDGNLCHA42fSeT7rTFa3s=,tag:Z6DNnKp1u9k/gAE8zpUtoA==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNEhoNHZVZTUzQUZVbTJs
            RHZjUkRtYWtyVnVkUEJUTnh5WStyTUpJN0hRClplQUtOZ0hlSVZBQmdKNjRIYXpx
            LzB4LytOQVAyVnBNNnRNeG1Udy9NVG8KLS0tIHRoVE1RbE03K2pXRktFMTJuMXdh
            ODJ0cDgxSXdHWVJVdzhEaXBVeXlzQVUKU5PD38Dn+HxZK07/Z7vb64irZzD0WQz8
            JKwHffHbG+fONyX1jtauFuOIwVc0DPxfbBqTm01cz/ypDlgLM88XsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:28:31Z"
    mac: ENC[AES256_GCM,data:Ucs53qIzO9d1RVrpkQE2n4X5eToNsl5014TezvorryybEy6vEFfq46P6yrO9LSBRCF7rj5I4CkqMXuRHDQAnKDMsdiDXavkA2dPIxtvTVTYzlIpChTFCaVdIXAtKRmu9fAhxnSO6T3M+OteNAEfdWm0N7XrJtiXsWoILmHvwPY4=,iv:XG4/NW6WfMN059V72tdTCWxOPwn5RylciUQcA5bU7cw=,tag:etMWJwudkq+ZroWfiMCVIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
