apiVersion: ENC[AES256_GCM,data:QdY=,iv:pTEWYYp6+USS1gMERjwijpxmXsAcmSkIJ1bX6C49GGw=,tag:Id1KFfvUz2dJAfh6c0bi9g==,type:str]
kind: ENC[AES256_GCM,data:m/7iKkFV,iv:5QNlf42IkxphNjoRV4p/2LcJLOuCx7Dt2t22C2bHiL8=,tag:v9SRuHeQIZdEMvD92uv7rQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AJMqEbQ7ceODQaY4,iv:xWBdGLYgp+TCLqNq0MPHHDZ6sLLrlsfAkDzxglDC4J0=,tag:CBuIYJe9qh2jGhmNnImOXw==,type:str]
    namespace: ENC[AES256_GCM,data:tvgNK5nDALEw,iv:VvQsgtxyDeWa0OMFTUCEEOmNXKaHme6ishHqaf8OsQw=,tag:Xpb51oKpCi3kk14qKaR2lw==,type:str]
type: ENC[AES256_GCM,data:pDCbxKsO,iv:y9zlljcy6VZnqqTvMK+WddvAnb5Xgysa/zSMdrNBpnA=,tag:vVBqluIMP8CS8H0FpSJs9w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:/fazNw==,iv:bU7gSfjJd2gU3Bvjjtklpn3TbzOw5arWRPC9inNcmFQ=,tag:5ibmwEp3UsH5JIOjUZ36zA==,type:str]
    password: ENC[AES256_GCM,data:CZCRDf7RZu90kwn60MTsXA==,iv:8VruyXiNpv4hRhCxOvmFg7j+OdcF4O7ZJz/IzwIon60=,tag:7ZfrMl0CBAGqaIIqh/tOng==,type:str]
    database: ENC[AES256_GCM,data:uoTs0/kgVqbC,iv:xAzzoxtdF9MD+aRwqcZJAOchNBWPvBUwPWKMdKhs+QI=,tag:+f25jque277IDX4D/wuCIw==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSW04MkFOdEtPWGRtd0l5
            UHZySmVJUTAxRlhhWG9UWkQ0aHhSNmhrNkZJCmNPQ04yeHcrcGp2MXlVUlo4VTNy
            VC9qWW5yeHZaQ1lrQmpQS0l3UzhXOTQKLS0tIHN0dWlVVHhIU2dLTUpRbUhzMkZs
            TjFqb2QyVjloVXprMGp0d2VOenpQa3MKSar+cYKmohiVJlnLDn5fjxEyK9xcFyAq
            1W5guB3ZRNH2H/aTmD7JnQ0nIigkEEzFHutxrOeRDs3oUk7WkMmqug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:01:29Z"
    mac: ENC[AES256_GCM,data:R5vkEwzrJHiAxv4z4lgsVvJusnGPfdHG85JR+ddfG7od6YjNdD/wkRVvEi5vUar5/rNMux4PreTFkSlIdpj1LDf43q+/hbwWGDCiRImXO4WUnS5PmCUWIEkn78CZLbDtTnASW5ScpatvqiUZ+cL6esxdaHs9nMokL9gqFNpDKPk=,iv:bMwEhyaUn1P8DSHUMjaZv1N47pPk7C5bkxLouagwUQc=,tag:MD7BMZXS8uh/TymwwUQSkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:Jvo=,iv:tBVSsWmZNwYmJuSi6t+zShMTEQpmPc54ZIR7+GZWaVI=,tag:Dc/V8NIF7ruOGtMqIPQFxg==,type:str]
kind: ENC[AES256_GCM,data:Qne3JvkF,iv:+IT3FON8SfxsnbLKsQdpg3ATOtFkiKsIPmIy+tLM160=,tag:THLjX+5/Ian2RZqM8nDizA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:03fHhsHzM1nG27utY+1q,iv:8RvLS8VEqxVhaDSrAvPGSlWSoHPQiyeqyIJZdBO1dlA=,tag:tXKCsXGsdl5PA7kBMWgORQ==,type:str]
    namespace: ENC[AES256_GCM,data:S3DsWjT68SAY,iv:Z1iwxZCu4WlxIJ/M0nsg3MaIwdKyk8v0VteQvLuR9OM=,tag:1WfWaCRn5WaP4bJc3G+JfQ==,type:str]
type: ENC[AES256_GCM,data:F6Jnmn/f,iv:TiLM3Ie3YTmXmSmOwr/nV63JevLUHwA7EbrseJ05KOA=,tag:SIMkScZvvot2BGL1Ziirzg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BzgG5A==,iv:J69DOvvllrltMw5QH/UUVWSgX/wvmHpcQ8PztpfTo0s=,tag:EnmxB7H6SsdzM9aGPfQ9zg==,type:str]
    password: ENC[AES256_GCM,data:yE5gRHu8bfBIt9chjApU/w==,iv:BH8M6Z8PpT4dgoO3JRIJ6irzfmL8NEM3NI0WXKYlRuA=,tag:/I3/RGzqm3ERPYUC0dLFXw==,type:str]
sops:
    age:
        - recipient: age1gyjyj6vlv32rxxgsz5fdlfkgj92redq42nlhf798df9f05pcrgsqa0lx0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSW04MkFOdEtPWGRtd0l5
            UHZySmVJUTAxRlhhWG9UWkQ0aHhSNmhrNkZJCmNPQ04yeHcrcGp2MXlVUlo4VTNy
            VC9qWW5yeHZaQ1lrQmpQS0l3UzhXOTQKLS0tIHN0dWlVVHhIU2dLTUpRbUhzMkZs
            TjFqb2QyVjloVXprMGp0d2VOenpQa3MKSar+cYKmohiVJlnLDn5fjxEyK9xcFyAq
            1W5guB3ZRNH2H/aTmD7JnQ0nIigkEEzFHutxrOeRDs3oUk7WkMmqug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T05:01:29Z"
    mac: ENC[AES256_GCM,data:R5vkEwzrJHiAxv4z4lgsVvJusnGPfdHG85JR+ddfG7od6YjNdD/wkRVvEi5vUar5/rNMux4PreTFkSlIdpj1LDf43q+/hbwWGDCiRImXO4WUnS5PmCUWIEkn78CZLbDtTnASW5ScpatvqiUZ+cL6esxdaHs9nMokL9gqFNpDKPk=,iv:bMwEhyaUn1P8DSHUMjaZv1N47pPk7C5bkxLouagwUQc=,tag:MD7BMZXS8uh/TymwwUQSkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
