apiVersion: batch/v1
kind: CronJob
metadata:
  name: open-meteo-scrape
  namespace: open-meteo
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scraper
              image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
              command:
                - /bin/sh
                - -c
                - |-
                  /scripts/scrape.sh
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
          volumes:
            - name: scripts
              configMap:
                name: open-meteo-scraper
                defaultMode: 0755
