apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - calibre-web
  - adguard-home
  - pairdrop
  - azalea-dev
  - radicale
  - open-meteo
  - ntfy
  - org-graphql
  - org-tides
  - ssh-pod
  # - jellyfin
