apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - kube-prometheus-stack.yaml
  - loki-stack.yaml
  - loki-external.yaml
  - ingress.yaml
  - dashboards
